name: Build docker image

on:
  create:
    tags:
      - v*

jobs:
  container-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: zekker6/slack-gitlab-mr-reminder
        tag_with_ref: true
        tag_with_sha: true
        dockerfile: docker/Dockerfile
        push: ${{ startsWith(github.ref, 'refs/tags/') }}